version: '3'
services:
  # MySQL database
  mysql:
    volumes:
      - ./database/mysql:/docker-entrypoint-initdb.d
      - mysql-volume:/var/lib/mysql
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $STUDENTFRIDGE_DB_PASSWORD
      MYSQL_DATABASE: $STUDENTFRIDGE_DB_NAME

  # PHPmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
  
  # student-fridge server and webapp
  student-fridge:
    #image: docker.pkg.github.com/antoine-gannat/student-fridge/student-fridge:latest
    build: .
    container_name: student-fridge
    volumes:
      - /etc/letsencrypt/live/student-fridge.fr/privkey.pem:/etc/letsencrypt/live/student-fridge.fr/privkey.pem
      - /etc/letsencrypt/live/student-fridge.fr/cert.pem:/etc/letsencrypt/live/student-fridge.fr/cert.pem
      - /etc/letsencrypt/live/student-fridge.fr/chain.pem:/etc/letsencrypt/live/student-fridge.fr/chain.pem
      - static-files-volume:/app/server/static-files
    environment:
     STUDENTFRIDGE_DB_HOST: mysql
     STUDENTFRIDGE_DB_PASSWORD: $STUDENTFRIDGE_DB_PASSWORD
     STUDENTFRIDGE_DB_NAME: $STUDENTFRIDGE_DB_NAME
     STUDENTFRIDGE_DB_USERNAME: $STUDENTFRIDGE_DB_USERNAME
     STUDENTFRIDGE_JWT_PASSWORD: $STUDENTFRIDGE_JWT_PASSWORD
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - mysql
    restart: always

volumes:
  mysql-volume:
  static-files-volume:
